name: Docker Build Production

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build Tagged Release
    uses: ./.github/workflows/publish.yml
    permissions:
      contents: read
      packages: write
    with:
      tag: ${{ github.event.release.tag_name }}
      tags: |
        ghcr.io/${{ github.repository }}:latest
